# Read data from record

In [47]:
import time
fd = open('data.json', 'r')

record=fd.read()
fd.close()

In [44]:
import json
item = json.loads(record)

In [45]:
item

{'1001': {'name': 'Barbon',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 50,
  'discount': 0},
 '1002': {'name': 'Barbon',
  'catogary': 'Chocolate',
  'price': 10,
  'quantity': 30,
  'discount': 0},
 '1004': {'name': 'Dairy Milk',
  'catogary': 'Chocolate',
  'price': 10,
  'quantity': 62,
  'discount': 0},
 '1005': {'name': 'Kitkat',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 42,
  'discount': 0},
 '1006': {'name': 'Kitkat',
  'catogary': 'Chocolate',
  'price': 20,
  'quantity': 53,
  'discount': 0},
 '1007': {'name': '5 star',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 100,
  'discount': 0},
 '1008': {'name': 'Galaxy',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 230,
  'discount': 0},
 '1009': {'name': 'Dairy Milk Silk',
  'catogary': 'Chocolate',
  'price': 50,
  'quantity': 30,
  'discount': 0},
 '1010': {'name': 'Nestle',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 23,
  'discount': 0},
 '1011': {'name': 'Cadbury',
  'catogary': 'Chocolate',
  'price': 10,
  'quantity': 150,
  'discount': 0},
 '1012': {'name': 'Amul',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 20,
  'discount': 0},
 '1013': {'name': 'Ferro Rocher',
  'catogary': 'Chocolate',
  'price': 15,
  'quantity': 560,
  'discount': 10},
 '1014': {'name': 'Hershey',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 500,
  'discount': 5},
 '1015': {'name': 'Mars',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 102,
  'discount': 0},
 '1016': {'name': 'Galaxy',
  'catogary': 'Chocolate',
  'price': 20,
  'quantity': 80,
  'discount': 0},
 '1017': {'name': 'Milkybar',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 90,
  'discount': 0},
 '1018': {'name': 'Amul Dark Chocolate',
  'catogary': 'Chocolate',
  'price': 80,
  'quantity': 70,
  'discount': 0},
 '1019': {'name': 'Ferrero Rocher Chocolate Balls',
  'catogary': 'Chocolate',
  'price': 50,
  'quantity': 150,
  'discount': 0},
 '1020': {'name': 'Dairy Milk',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 50,
  'discount': 0},
 '1021': {'name': 'Lottry Choco Pie',
  'catogary': 'Cup Cake/Choco Pie',
  'price': 10,
  'quantity': 90,
  'discount': 0},
 '1022': {'name': 'Sprite',
  'catogary': 'Soft Drink',
  'price': 90,
  'quantity': 700,
  'discount': 0},
 '1023': {'name': 'fruty',
  'catogary': 'Soft Drink',
  'price': 100,
  'quantity': 750,
  'discount': 0},
 '1024': {'name': 'Maza',
  'catogary': 'Soft Drink',
  'price': 90,
  'quantity': 560,
  'discount': 0},
 '1003': {'name': 'Kit-Kat',
  'catogary': 'Chocolate',
  'price': 50,
  'quantity': 155,
  'discount': 0}}

In [28]:
item['1001']

{'name': 'Barbon',
 'catogary': 'Chocolate',
 'price': 5,
 'quantity': 50,
 'discount': 0}

# Add New Item into Record

In [48]:
print("*********************************************")
print("          Welcome to Sagar Store           ")
prod_id = str(input("Enter product id:"))
name = str(input("Enter product name:"))
catogary = str(input("Enter product catogary:"))
price = int(input("Enter product price:"))
quantity = int(input("Enter product quantity:"))
discount = int(input("Enter discount on product :"))

item[prod_id] = {'name': name, 'catogary': catogary, 'price': price, 'quantity': quantity,'discount': discount }

# if(record[prod_id]==prod_id):
#     print("product aready")

js = json.dumps(item)

fd = open("data.json",'w')
fd.write(js)
fd.close()
print("Record has been updated")
print(time.ctime())
print("****Thankyou****")

*********************************************
          Welcome to Sagar Store
Enter product id:1025
Enter product name:KissMe
Enter product catogary:Toffy
Enter product price:2
Enter product quantity:1000
Enter discount on product :0
Record has been updated
Sun Sep  5 23:42:47 2021

In [46]:
item

{'1001': {'name': 'Barbon',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 50,
  'discount': 0},
 '1002': {'name': 'Barbon',
  'catogary': 'Chocolate',
  'price': 10,
  'quantity': 30,
  'discount': 0},
 '1004': {'name': 'Dairy Milk',
  'catogary': 'Chocolate',
  'price': 10,
  'quantity': 62,
  'discount': 0},
 '1005': {'name': 'Kitkat',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 42,
  'discount': 0},
 '1006': {'name': 'Kitkat',
  'catogary': 'Chocolate',
  'price': 20,
  'quantity': 53,
  'discount': 0},
 '1007': {'name': '5 star',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 100,
  'discount': 0},
 '1008': {'name': 'Galaxy',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 230,
  'discount': 0},
 '1009': {'name': 'Dairy Milk Silk',
  'catogary': 'Chocolate',
  'price': 50,
  'quantity': 30,
  'discount': 0},
 '1010': {'name': 'Nestle',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 23,
  'discount': 0},
 '1011': {'name': 'Cadbury',
  'catogary': 'Chocolate',
  'price': 10,
  'quantity': 150,
  'discount': 0},
 '1012': {'name': 'Amul',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 20,
  'discount': 0},
 '1013': {'name': 'Ferro Rocher',
  'catogary': 'Chocolate',
  'price': 15,
  'quantity': 560,
  'discount': 10},
 '1014': {'name': 'Hershey',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 500,
  'discount': 5},
 '1015': {'name': 'Mars',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 102,
  'discount': 0},
 '1016': {'name': 'Galaxy',
  'catogary': 'Chocolate',
  'price': 20,
  'quantity': 80,
  'discount': 0},
 '1017': {'name': 'Milkybar',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 90,
  'discount': 0},
 '1018': {'name': 'Amul Dark Chocolate',
  'catogary': 'Chocolate',
  'price': 80,
  'quantity': 70,
  'discount': 0},
 '1019': {'name': 'Ferrero Rocher Chocolate Balls',
  'catogary': 'Chocolate',
  'price': 50,
  'quantity': 150,
  'discount': 0},
 '1020': {'name': 'Dairy Milk',
  'catogary': 'Chocolate',
  'price': 5,
  'quantity': 50,
  'discount': 0},
 '1021': {'name': 'Lottry Choco Pie',
  'catogary': 'Cup Cake/Choco Pie',
  'price': 10,
  'quantity': 90,
  'discount': 0},
 '1022': {'name': 'Sprite',
  'catogary': 'Soft Drink',
  'price': 90,
  'quantity': 700,
  'discount': 0},
 '1023': {'name': 'fruty',
  'catogary': 'Soft Drink',
  'price': 100,
  'quantity': 750,
  'discount': 0},
 '1024': {'name': 'Maza',
  'catogary': 'Soft Drink',
  'price': 90,
  'quantity': 560,
  'discount': 0},
 '1003': {'name': 'Kit-Kat',
  'catogary': 'Chocolate',
  'price': 50,
  'quantity': 155,
  'discount': 0}}